class Localization {
  static const Map<String, Map<String, String>> _strings = {
    'ko-KR': {
      // Sidebar
      'tab_explore': '모드 탐색',
      'tab_installed': '설치 관리',
      'tab_settings': '환경 설정',
      'sidebar_games_title': '대상 게임 (GAMES)',
      'sidebar_adofai_sub': '얼불춤 (Active)',
      'sidebar_adofai_tooltip': 'A Dance of Fire and Ice 모드 매니저가 활성화 상태입니다.',
      'sidebar_rd_sub': '리듬닥터 (Coming Soon)',
      'sidebar_rd_tooltip': 'Rhythm Doctor 모드 매니저는 곧 지원 예정입니다.',

      // Settings Tab
      'settings_title': '설정 (SETTINGS)',
      'settings_game_path_title': '얼불춤 게임 설치 경로 설정',
      'settings_path_empty': '게임 경로가 지정되지 않았습니다. 폴더를 선택해 주세요.',
      'settings_path_invalid': '⚠️ 해당 경로에 게임 실행 파일(A Dance of Fire and Ice)이 존재하지 않습니다.',
      'settings_btn_select_manually': '폴더 수동 선택',
      'settings_btn_auto_detect': '스팀 경로 자동 감지',
      'settings_api_title': 'modlist.org API 서버 연동',
      'settings_btn_save': '저장',
      'settings_api_guide': '기본값은 https://modlist.org 이며 로컬 테스트 시 http://localhost:3000 으로 변경 가능합니다.',
      'settings_sys_title': '시스템 정보',
      'settings_sys_os': '운영체제(OS)',
      'settings_sys_ver': '프로그램 버전',
      'settings_sys_loader': '로더 타입',
      'settings_lang_title': '언어 설정 (Language)',
      'settings_api_saved': 'API URL 설정이 저장되었습니다.',
      'settings_path_detected': '얼불춤 스팀 기본 경로를 자동으로 설정했습니다.',
      'settings_path_not_found': '스팀 기본 경로에서 얼불춤 설치 폴더를 찾을 수 없습니다. 수동으로 선택해 주세요.',

      // Installed Tab
      'installed_title': '설치 관리 (INSTALLED)',
      'installed_loader_title': 'MelonLoader 관리',
      'installed_loader_active': 'MelonLoader가 활성화되어 있습니다. (v{version})',
      'installed_loader_inactive': 'MelonLoader가 설치되어 있지 않습니다.',
      'installed_loader_outdated_title': '구버전 MelonLoader가 감지되었습니다.',
      'installed_loader_umm_title': 'Unity Mod Manager(UMM)가 감지되었습니다.',
      'installed_btn_update_loader': 'v{version}로 업데이트',
      'installed_btn_uninstall': '제거 (Uninstall)',
      'installed_btn_replace_loader': 'MelonLoader로 교체 설치',
      'installed_btn_install': '설치 (Install)',
      'installed_loader_outdated_banner': '현재 감지된 MelonLoader 버전은 {version} 입니다.\n구버전 또는 외부에서 설치된 모드로더는 오류를 유발할 수 있으므로 최신 v{targetVersion}로 업데이트해 주세요.',
      'installed_umm_banner': '현재 게임 폴더 내에 Unity Mod Manager(UMM)가 설치되어 있는 것이 확인되었습니다.\nmodlist.org 앱의 모드들을 완벽히 연동(설치/삭제/업데이트)하려면 MelonLoader가 필수적입니다.\n위의 [MelonLoader로 교체 설치] 버튼을 누르면 기존 UMM을 지우고 MelonLoader 설치를 자동으로 진행합니다.',
      'replace_umm_dialog_title': 'Unity Mod Manager 교체 및 모드 이관',
      'replace_umm_dialog_body': '기존 Mods 폴더에 있는 UMM 모드들을 UMMMods 폴더로 안전하게 이관합니다.\n\n또한, 이관된 UMM 모드들이 MelonLoader에서 정상적으로 작동하도록 UMM 호환 모드(ummcompat)를 추가로 설치하시겠습니까?',
      'replace_umm_dialog_btn_yes': '예 (호환 모드 설치)',
      'replace_umm_dialog_btn_no': '아니오 (호환 모드 미설치)',
      'replace_umm_dialog_btn_cancel': '취소',
      'installed_list_title': '설치된 모드 목록',
      'installed_btn_add_mod_manually': '파일에서 모드 설치',
      'installed_no_mods': '설치된 모드가 없습니다.',
      'installed_ver_prefix': '설치 버전: v{version}',
      'installed_latest_ver_prefix': '최신 버전: v{version}',
      'installed_game_ver_prefix': '지원 게임: {version}',
      'installed_btn_update_mod': '업데이트',
      'installed_btn_delete_mod': '삭제',
      'installed_copied_clipboard': '클립보드에 복사되었습니다.',

      // Explore Tab
      'explore_filter_category': '카테고리',
      'explore_filter_category_all': '전체 카테고리',
      'category_ui': 'UI',
      'category_gameplay': '게임플레이',
      'category_utility': '유틸리티',
      'category_visuals': '비주얼',
      'category_library': '라이브러리',
      'explore_filter_sort': '정렬 기준',
      'explore_filter_sort_downloads': '다운로드 많은 순',
      'explore_filter_sort_downloads_asc': '다운로드 적은 순',
      'explore_filter_sort_updated': '최근 업데이트 순',
      'explore_filter_sort_created': '최근 등록 순',
      'explore_filter_sort_name': '이름순 (A-Z)',
      'explore_filter_sort_name_desc': '이름순 (Z-A)',
      'explore_search_placeholder': '모드 이름 또는 설명 검색...',
      'explore_no_mods_found': '조건에 맞는 모드를 찾을 수 없습니다.',
      'explore_badge_update_req': '업데이트 필요',
      'explore_badge_installed': '설치 완료',
      'explore_card_featured': '추천',
      'explore_modal_categories': '카테고리',
      'explore_modal_downloads': '다운로드 수',
      'explore_modal_author': '제작자',
      'explore_modal_collaborators': '협업자',
      'explore_modal_latest_ver': '최신 버전',
      'explore_modal_game_ver': '권장 게임 버전',
      'explore_modal_downloads_unit': '{count}회',
      'explore_modal_err_title': '오류',
      'explore_modal_err_body': '모드 상세 정보를 불러올 수 없습니다.',
      'explore_modal_btn_close': '닫기',
      'explore_modal_btn_delete': '모드 삭제',
      'explore_modal_btn_install': '모드 설치 (Install)',
      'explore_modal_warn_path': '⚠️ 설정 탭에서 올바른 게임 설치 경로를 먼저 지정해 주세요.',
      'explore_modal_warn_loader': '모드를 설치하려면 먼저 MelonLoader 설치가 필요합니다.',
      'explore_modal_btn_auto_loader': 'MelonLoader 자동 설치',
      'explore_modal_loading': '처리 중...',
      "explore_modal_expand": "펼치기",
      'explore_card_author_more': ' 외',
      'game_adofai': '얼불춤 (ADOFAI)',
      'explore_modal_beta': '베타'
    },
    'en-US': {
      // Sidebar
      'tab_explore': 'Explore',
      'tab_installed': 'Installed',
      'tab_settings': 'Settings',
      'sidebar_games_title': 'TARGET GAMES',
      'sidebar_adofai_sub': 'ADOFAI (Active)',
      'sidebar_adofai_tooltip': 'A Dance of Fire and Ice mod manager is active.',
      'sidebar_rd_sub': 'Rhythm Doctor (Coming Soon)',
      'sidebar_rd_tooltip': 'Rhythm Doctor mod manager is coming soon.',

      // Settings Tab
      'settings_title': 'Settings',
      'settings_game_path_title': 'ADOFAI Game Directory Settings',
      'settings_path_empty': 'Game directory is not specified. Please select a folder.',
      'settings_path_invalid': '⚠️ Game executable (A Dance of Fire and Ice) does not exist in this directory.',
      'settings_btn_select_manually': 'Select Folder Manually',
      'settings_btn_auto_detect': 'Auto-Detect Steam Path',
      'settings_api_title': 'modlist.org API Connection',
      'settings_btn_save': 'Save',
      'settings_api_guide': 'Default is https://modlist.org. Can be changed to http://localhost:3000 for local testing.',
      'settings_sys_title': 'System Info',
      'settings_sys_os': 'Operating System (OS)',
      'settings_sys_ver': 'Program Version',
      'settings_sys_loader': 'Loader Type',
      'settings_lang_title': 'Language Setting',
      'settings_api_saved': 'API URL setting saved successfully.',
      'settings_path_detected': 'ADOFAI default Steam directory set automatically.',
      'settings_path_not_found': 'Cannot find ADOFAI installation directory in default Steam path. Please select manually.',

      // Installed Tab
      'installed_title': 'Installed Mods',
      'installed_loader_title': 'MelonLoader Management',
      'installed_loader_active': 'MelonLoader is active. (v{version})',
      'installed_loader_inactive': 'MelonLoader is not installed.',
      'installed_loader_outdated_title': 'Outdated MelonLoader detected.',
      'installed_loader_umm_title': 'Unity Mod Manager (UMM) detected.',
      'installed_btn_update_loader': 'Update to v{version}',
      'installed_btn_uninstall': 'Uninstall',
      'installed_btn_replace_loader': 'Replace with MelonLoader',
      'installed_btn_install': 'Install',
      'installed_loader_outdated_banner': 'Currently detected MelonLoader version is {version}.\nUsing outdated or external mod loaders may cause errors. Please update to the latest v{targetVersion}.',
      'installed_umm_banner': 'Unity Mod Manager (UMM) has been detected in the game folder.\nMelonLoader is required to seamlessly manage (install/delete/update) mods via modlist.org.\nClicking [Replace with MelonLoader] will wipe UMM and automatically set up MelonLoader.',
      'replace_umm_dialog_title': 'Replace Unity Mod Manager & Migrate Mods',
      'replace_umm_dialog_body': 'We will safely migrate the UMM mods in the existing Mods folder to the UMMMods folder.\n\nIn addition, would you like to install the UMM compatibility mod (ummcompat) so that the migrated UMM mods work properly under MelonLoader?',
      'replace_umm_dialog_btn_yes': 'Yes (Install Compatibility Mod)',
      'replace_umm_dialog_btn_no': 'No (Do Not Install)',
      'replace_umm_dialog_btn_cancel': 'Cancel',
      'installed_list_title': 'Installed Mods List',
      'installed_btn_add_mod_manually': 'Install Mod from File',
      'installed_no_mods': 'No installed mods.',
      'installed_ver_prefix': 'Installed: v{version}',
      'installed_latest_ver_prefix': 'Latest: v{version}',
      'installed_game_ver_prefix': 'Req. Game: {version}',
      'installed_btn_update_mod': 'Update',
      'installed_btn_delete_mod': 'Delete',
      'installed_copied_clipboard': 'Copied to clipboard.',

      // Explore Tab
      'explore_filter_category': 'Category',
      'explore_filter_category_all': 'All Categories',
      'category_ui': 'UI',
      'category_gameplay': 'Gameplay',
      'category_utility': 'Utility',
      'category_visuals': 'Visuals',
      'category_library': 'Library',
      'explore_filter_sort': 'Sort By',
      'explore_filter_sort_downloads': 'Most Downloaded',
      'explore_filter_sort_downloads_asc': 'Least Downloaded',
      'explore_filter_sort_updated': 'Recently Updated',
      'explore_filter_sort_created': 'Recently Added',
      'explore_filter_sort_name': 'Name (A-Z)',
      'explore_filter_sort_name_desc': 'Name (Z-A)',
      'explore_search_placeholder': 'Search mod name or description...',
      'explore_no_mods_found': 'No matching mods found.',
      'explore_badge_update_req': 'Update Req.',
      'explore_badge_installed': 'Installed',
      'explore_card_featured': 'Featured',
      'explore_modal_categories': 'Category',
      'explore_modal_downloads': 'Downloads',
      'explore_modal_author': 'Author',
      'explore_modal_collaborators': 'Collaborators',
      'explore_modal_latest_ver': 'Latest Version',
      'explore_modal_game_ver': 'Req. Game Ver.',
      'explore_modal_downloads_unit': '{count} times',
      'explore_modal_err_title': 'Error',
      'explore_modal_err_body': 'Could not load mod details.',
      'explore_modal_btn_close': 'Close',
      'explore_modal_btn_delete': 'Delete Mod',
      'explore_modal_btn_install': 'Install Mod',
      'explore_modal_warn_path': '⚠️ Please set a valid game path in the settings tab first.',
      'explore_modal_warn_loader': 'MelonLoader installation is required first to install mods.',
      'explore_modal_btn_auto_loader': 'Auto-Install MelonLoader',
      'explore_modal_loading': 'Processing...',
      "explore_modal_expand": "Expend",
      'explore_card_author_more': ' and more',
      'game_adofai': 'ADOFAI',
      'explore_modal_beta': 'Beta'
    }
  };

  static String get(String locale, String key, {Map<String, String>? args}) {
    final language = _strings[locale] ?? _strings['en-US']!;
    var text = language[key] ?? _strings['en-US']![key] ?? key;
    
    if (args != null) {
      args.forEach((k, v) {
        text = text.replaceAll('{$k}', v);
      });
    }
    
    return text;
  }
}
