display_name: modlist.org
package_name: modlist-org-app
maintainer:
  name: modlist.org
  email: admin@modlist.org
installed_size: 50000
priority: optional
section: x11
icon: web/icons/Icon-512.png
summary: modlist.org desktop client
description: The official desktop app for installing and managing game mods from modlist.org.
categories:
  - Utility
keywords:
  - game
  - mod
  - installer
  - adofai
